[package]
name = "tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25"
sysinfo = "0.29.10"
rand = "0.8.5"
ratatui = "0.23.0"
battery = "0.7.8"
